"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import type { HermesRuntimeSnapshot, ToolDescriptor } from "@/lib/runtime";

const labels: Record<string, string> = { available: "可用", partial: "部分可用", unsupported: "不支援", unknown: "未知", stale: "過期", failed: "失敗", syncing: "同步中" };
const statusLabel = (value: string) => labels[value] || value;
function ToolRow({ tool }: { tool: ToolDescriptor }) {
  const [open, setOpen] = useState(false);
  return <li className="runtime-tool"><button type="button" className="runtime-tool-summary" onClick={() => setOpen(v => !v)} aria-expanded={open}><span className={`runtime-status-dot ${tool.status}`} aria-hidden="true" /><strong>{tool.displayName}</strong><small>{tool.canonicalName} · {statusLabel(tool.status)}</small></button>{open && <div className="runtime-tool-detail"><p>{tool.description || "未提供描述。"}</p><dl><dt>來源</dt><dd>{tool.sourceServer || tool.source}</dd><dt>權限</dt><dd>{tool.permissions.join("、")}</dd><dt>最後驗證</dt><dd>{tool.lastVerifiedAt ? new Date(tool.lastVerifiedAt).toLocaleString("zh-TW") : "未知"}</dd><dt>專案／Agent</dt><dd>{tool.projectScope === "all" ? "全部專案" : tool.projectScope.join("、")} · {tool.agentScope === "all" ? "全部 Agent" : tool.agentScope.join("、")}</dd></dl><details><summary>Input schema</summary><pre>{JSON.stringify(tool.inputSchema, null, 2)}</pre></details></div>}</li>;
}
export default function RuntimeInspector() {
  const [snapshot, setSnapshot] = useState<HermesRuntimeSnapshot | null>(null), [stale, setStale] = useState(false), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const load = useCallback(async () => { try { const response = await fetch("/api/runtime", { cache: "no-store", signal: AbortSignal.timeout(40_000) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "無法讀取 Hermes Runtime。"); setSnapshot(result.snapshot); setStale(!!result.stale); } catch (e) { setError((e as Error).message); } }, []);
  const refresh = async () => { setBusy(true); setError(""); try { const response = await fetch("/api/runtime", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ refresh: true }), signal: AbortSignal.timeout(60_000) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Runtime 同步失敗。"); setSnapshot(result.snapshot); setStale(false); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  useEffect(() => { void load(); const stream = new EventSource("/api/runtime/events"); const onSnapshot = (event: Event) => { try { const next = JSON.parse((event as MessageEvent).data) as HermesRuntimeSnapshot; setSnapshot(next); setStale(next.status === "stale"); setError(""); } catch { setError("Runtime 事件格式無法解析。"); } }; const onError = () => { setStale(true); void load(); }; stream.addEventListener("runtime.snapshot", onSnapshot); stream.addEventListener("runtime.error", onError); stream.onerror = onError; return () => stream.close(); }, [load]);
  const groups = useMemo(() => { const map = new Map<string, ToolDescriptor[]>(); for (const tool of snapshot?.tools || []) { const key = tool.sourceServer || tool.source; map.set(key, [...(map.get(key) || []), tool]); } return [...map.entries()]; }, [snapshot]);
  return <section className="runtime-inspector" aria-label="Hermes Runtime 狀態"><header><div><p className="eyebrow">Hermes Runtime · Source of Truth</p><h2>即時能力同步</h2></div><div className="runtime-actions"><button onClick={() => void refresh()} disabled={busy}>{busy ? "同步中…" : "重新同步"}</button><span className={`runtime-state ${stale || snapshot?.status === "stale" ? "stale" : snapshot?.status || "unknown"}`}>{snapshot ? statusLabel(stale ? "stale" : snapshot.status) : "尚未同步"}</span></div></header>{error && <p role="alert">{error}</p>}{snapshot && <><p className="muted">最後同步：{new Date(snapshot.lastSyncedAt).toLocaleString("zh-TW")} · snapshot {snapshot.hash.slice(0, 10)} · {snapshot.diagnostics.toolCount} 個工具／{snapshot.diagnostics.skillCount} 個技能／{snapshot.diagnostics.toolsetCount} 個 Toolset</p>{snapshot.errors.map(message => <p key={message} className="error">{message}</p>)}<div className="runtime-summary"><span>Agent {snapshot.agents.length}</span><span>模型 {snapshot.models.length}</span><span>MCP {snapshot.mcpServers.length}</span><span>Sessions {statusLabel(snapshot.sessionsSupport)}</span><span>Runs {statusLabel(snapshot.runsSupport)}</span><span>Memory {statusLabel(snapshot.memorySupport)}</span></div><div className="runtime-tool-groups">{groups.map(([source, tools]) => <details key={source} open><summary>{source} · {tools.length} 個工具</summary><ul>{tools.map(tool => <ToolRow key={tool.canonicalName} tool={tool} />)}</ul></details>)}</div>{!groups.length && <p>Runtime 尚未列出工具；這不代表工具已可用。</p>}</>}</section>;
}
